#!/usr/bin/env python3
"""Bakes the animated OpenAI logo gif into firmware/src/logo_codex_anim.h as a
hi-res bitmap animation: PX x PX, 4-bit grayscale (16 levels), two pixels per
byte. Played by header_codex_logo() in firmware/src/proto.cpp.

Why this exists: the splash-mini engine renders on a fixed 20x20 cell grid,
which made the knot look blocky on the Codex view. This path keeps full
detail with real anti-aliasing. The knot is NOT in the splash engine's
claudepix_data set - this is its only firmware representation.

Source gif: assets/openai_logo_animation.gif (white knot on black, 671x671;
scanlines -> arcs -> knot -> hold -> loop).

Two rules earn their keep here:

1. The crop is sized off the SETTLED KNOT, not the union of every frame.
   The build-up phase sweeps arcs wider than the finished knot, so a union
   crop left the steady-state mark filling only ~64% of the canvas - it read
   as a small logo next to the Grok mark, which fills its box. Cropping to
   knot_bbox / KNOT_FRAC makes the resting knot the thing that fills the
   frame; the widest build-up frames lose a few edge pixels (reported below).

2. Consecutive identical frames collapse into one entry + a hold count.
   The gif's "slow spin" tail is not a spin at all: frames 78..168 were
   byte-identical, i.e. 91 duplicate frames costing ~290 KB of flash to hold
   a still image. They are now one frame with a hold, so the device shows the
   same pause for a fraction of the flash.
"""

from pathlib import Path

from PIL import Image, ImageSequence

ROOT = Path(__file__).resolve().parent.parent
GIF = ROOT / "assets" / "openai_logo_animation.gif"
OUT = ROOT / "firmware" / "src" / "logo_codex_anim.h"

PX = 100                # canvas is PX x PX on-device
T_BG = 28               # luminance below this is background (bbox threshold)
KNOT_FRAC = 0.92        # settled knot fills this fraction of the canvas
SETTLED_FROM = 78       # frames from here on are the resting knot
HOLD_CAP = 60           # ticks; the gif rests ~15s on the knot, which reads as frozen


def bbox_of(frame: Image.Image):
    return frame.point(lambda v: 255 if v >= T_BG else 0).getbbox()


def union(boxes):
    xs0, ys0, xs1, ys1 = zip(*[b for b in boxes if b])
    return min(xs0), min(ys0), max(xs1), max(ys1)


def main() -> None:
    im = Image.open(GIF)
    raws = [f.convert("L").copy() for f in ImageSequence.Iterator(im)]
    W, H = im.size
    print(f"{GIF.name}: {len(raws)} frames, {W}x{H}")

    boxes = [bbox_of(f) for f in raws]
    # Drop any near-empty lead-in (no-op for the current gif).
    start = next(i for i, b in enumerate(boxes) if b)
    raws, boxes = raws[start:], boxes[start:]

    # Crop off the settled knot so IT fills the canvas (rule 1 above).
    kx0, ky0, kx1, ky1 = union(boxes[SETTLED_FROM:])
    cx, cy = (kx0 + kx1) / 2, (ky0 + ky1) / 2
    half = max(kx1 - kx0, ky1 - ky0) / 2 / KNOT_FRAC
    half = min(half, cx, cy, W - cx, H - cy)
    box = (int(cx - half), int(cy - half), int(cx + half), int(cy + half))
    print(f"settled knot {(kx0, ky0, kx1, ky1)} -> crop {box} ({box[2] - box[0]}px square)")

    # How much of the wider build-up phase falls outside that crop.
    ax0, ay0, ax1, ay1 = union(boxes)
    over = max(box[0] - ax0, box[1] - ay0, ax1 - box[2], ay1 - box[3], 0)
    print(f"build-up overshoot: {over}px of source ({over / (box[2] - box[0]) * PX:.1f}px on canvas)")

    grids = [list(f.crop(box).resize((PX, PX), Image.LANCZOS).getdata()) for f in raws]

    # Collapse runs of identical frames into one entry + a hold count (rule 2).
    packed_frames, holds = [], []
    for g in grids:
        nib = [(v * 15 + 127) // 255 for v in g]
        row = bytes((nib[i] << 4) | nib[i + 1] for i in range(0, PX * PX, 2))
        if packed_frames and row == packed_frames[-1]:
            holds[-1] = min(holds[-1] + 1, HOLD_CAP)
        else:
            packed_frames.append(row)
            holds.append(1)
    print(f"{len(grids)} frames -> {len(packed_frames)} unique "
          f"(longest hold {max(holds)} ticks)")

    lines = [
        "#pragma once",
        "// Generated by tools/gif_to_bitmap_c.py from assets/openai_logo_animation.gif",
        "// - do not edit. PX x PX, 4-bit grayscale, two pixels per byte (hi nibble",
        "// first). Each frame carries a hold count in ticks: runs of identical",
        "// source frames are stored once (the gif's tail is a still hold, not a",
        "// spin). Played by header_codex_logo() in proto.cpp, which paints the",
        "// grey level as ALPHA on white so the mark composites over the view.",
        f"#define CODEX_ANIM_PX {PX}",
        f"#define CODEX_ANIM_FRAMES {len(packed_frames)}",
        f"#define CODEX_ANIM_FRAME_BYTES {PX * PX // 2}",
        "static const uint8_t codex_anim_holds[CODEX_ANIM_FRAMES] = {",
        "    " + ",".join(str(h) for h in holds),
        "};",
        "static const uint8_t codex_anim_frames[CODEX_ANIM_FRAMES][CODEX_ANIM_FRAME_BYTES] = {",
    ]
    for row in packed_frames:
        lines.append("    {" + ",".join(str(b) for b in row) + "},")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB, "
          f"{len(packed_frames) * PX * PX // 2} bytes of flash)")


if __name__ == "__main__":
    main()
