#!/usr/bin/env python3
"""Bakes the animated OpenAI logo gif into firmware/src/logo_codex_anim.h as a
hi-res bitmap animation: 80x80 px, 4-bit grayscale (16 levels), two pixels per
byte. Played by header_codex_logo() in firmware/src/proto.cpp.

Why this exists: the splash-mini engine renders on a fixed 20x20 cell grid,
which made the knot look blocky on the Codex view. This path keeps full 80x80
detail with real anti-aliasing. The knot is NOT in the splash engine's
claudepix_data set — this is its only firmware representation.

Source gif: assets/openai_logo_animation.gif (white knot on black, 671x671;
scanlines -> arcs -> knot -> slow spin -> loop). Uses the same fixed-crop rule
as the 20x20 converter did: one shared square crop (union bbox + margin) for
all frames so the knot stays centred and constant-size.

The spin phase (from SPIN_START on) is nearly static per frame, so it is
thinned 2:1 — halves flash use, visibly identical at the 80ms device tick.

Usage: .venv/Scripts/python.exe tools/gif_to_bitmap_c.py
Writes: firmware/src/logo_codex_anim.h
"""

from pathlib import Path

from PIL import Image, ImageSequence

ROOT = Path(__file__).resolve().parent.parent
GIF = ROOT / "assets" / "openai_logo_animation.gif"
OUT = ROOT / "firmware" / "src" / "logo_codex_anim.h"

PX = 80                 # canvas is 80x80 on-device
T_BG = 28               # luminance below this is background (bbox threshold)
MARGIN = 1.04           # fixed-crop padding around the union bbox
SPIN_START = 70         # knot fully formed from here on (thin 2:1 past this)
SPIN_KEEP_EVERY = 2


def occupancy(frame: Image.Image) -> int:
    h = frame.histogram()
    return sum(h[T_BG:])


def main() -> None:
    im = Image.open(GIF)
    raws = [f.convert("L").copy() for f in ImageSequence.Iterator(im)]
    print(f"{GIF.name}: {len(raws)} frames, {im.size[0]}x{im.size[1]}")

    # Drop any near-empty lead-in (no-op for the current gif).
    peak = max(occupancy(f) for f in raws)
    start = next(i for i, f in enumerate(raws) if occupancy(f) >= peak * 0.05)
    raws = raws[start:]

    # One fixed square crop for the whole loop.
    x0, y0, x1, y1 = 1 << 30, 1 << 30, -1, -1
    for f in raws:
        bb = f.point(lambda v: 255 if v >= T_BG else 0).getbbox()
        if bb:
            x0, y0 = min(x0, bb[0]), min(y0, bb[1])
            x1, y1 = max(x1, bb[2]), max(y1, bb[3])
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    half = max(x1 - x0, y1 - y0) / 2 * MARGIN
    W, H = im.size
    half = min(half, cx, cy, W - cx, H - cy)
    box = (int(cx - half), int(cy - half), int(cx + half), int(cy + half))
    print(f"fixed crop {box} ({box[2] - box[0]}px square)")

    grids = []
    for f in raws:
        small = f.crop(box).resize((PX, PX), Image.LANCZOS)
        grids.append(list(small.getdata()))

    keep = list(range(0, SPIN_START)) + list(range(SPIN_START, len(grids), SPIN_KEEP_EVERY))
    print(f"keeping {len(keep)} of {len(grids)} frames (spin thinned {SPIN_KEEP_EVERY}:1 from frame {SPIN_START})")

    lines = [
        "#pragma once",
        "// Generated by tools/gif_to_bitmap_c.py from assets/openai_logo_animation.gif",
        "// - do not edit. 80x80 px, 4-bit grayscale, two pixels per byte (hi nibble",
        "// first). Played by header_codex_logo() in proto.cpp.",
        f"#define CODEX_ANIM_PX {PX}",
        f"#define CODEX_ANIM_FRAMES {len(keep)}",
        f"#define CODEX_ANIM_FRAME_BYTES {PX * PX // 2}",
        "static const uint8_t codex_anim_frames[CODEX_ANIM_FRAMES][CODEX_ANIM_FRAME_BYTES] = {",
    ]
    for ki in keep:
        nibbles = [(v * 15 + 127) // 255 for v in grids[ki]]
        packed = [str((nibbles[i] << 4) | nibbles[i + 1]) for i in range(0, PX * PX, 2)]
        lines.append("    {" + ",".join(packed) + "},")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")
    kb = OUT.stat().st_size // 1024
    print(f"wrote {OUT} ({kb} KB)")


if __name__ == "__main__":
    main()
